web:
  labels:
    - convox.port.443.protocol=https
    - convox.port.22.protocol=tls
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'git.fixdapp.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://git.fixdapp.com'
      unicorn['port'] = 8080
      # nginx['enable'] = false
      nginx['listen_port'] = 80
      nginx['listen_https'] = false
      # nginx['proxy_set_headers'] = {
      #   "X-Forwarded-Proto" => "https",
      #   "X-Forwarded-Ssl" => "on"
      # }
      postgresql['enable'] = false
      gitlab_rails['db_adapter'] = 'postgresql'
      gitlab_rails['db_encoding'] = 'utf8'
      gitlab_rails['db_database'] = ENV['POSTGRES_PATH'].gsub('/', '')
      gitlab_rails['db_host'] = ENV['POSTGRES_HOST']
      gitlab_rails['db_port'] = ENV['POSTGRES_PORT']
      gitlab_rails['db_username'] = ENV['POSTGRES_USERNAME']
      gitlab_rails['db_password'] = ENV['POSTGRES_PASSWORD']
      redis['enable'] = false
      gitlab_rails['redis_host'] = ENV['REDIS_HOST']
      gitlab_rails['redis_port'] = ENV['REDIS_PORT']
      gitlab_rails['redis_password'] = ENV['REDIS_PASSWORD']
  ports:
    - '80:80'
    - '443:80'
    - '22:22'
  volumes:
    - /etc/gitlab
    - /var/log/gitlab
    - /var/opt/gitlab
  links:
    - redis
    - postgres
redis:
  image: convox/redis
  ports:
    - 6379
postgres:
  image: convox/postgres
  ports:
    - 5432
  volumes:
    - /var/lib/postgresql/data